version: '3'
services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb_service
    hostname: mongodb_service
    restart: always
    ports:
     - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - authdb:/data/db
  mongo-express:
    image: mongo-express:1.0.0-20
    container_name: mongo-express_service
    hostname: mongo-express_service
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
volumes:
  authdb:
    driver: local
